# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import getStudent_pb2 as proto_dot_getStudent__pb2


class getStudentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getByID = channel.unary_unary(
                '/getStudent/getByID',
                request_serializer=proto_dot_getStudent__pb2.inputSID.SerializeToString,
                response_deserializer=proto_dot_getStudent__pb2.studentInfo.FromString,
                )


class getStudentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getByID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_getStudentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getByID': grpc.unary_unary_rpc_method_handler(
                    servicer.getByID,
                    request_deserializer=proto_dot_getStudent__pb2.inputSID.FromString,
                    response_serializer=proto_dot_getStudent__pb2.studentInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'getStudent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL SERVER.
class getStudent(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getByID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/getStudent/getByID',
            proto_dot_getStudent__pb2.inputSID.SerializeToString,
            proto_dot_getStudent__pb2.studentInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
