# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/getStudent.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/getStudent.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16proto/getStudent.proto\"\x17\n\x08inputSID\x12\x0b\n\x03sid\x18\x01 \x01(\x04\"o\n\x0bstudentInfo\x12\x0b\n\x03sid\x18\x01 \x01(\x04\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06gender\x18\x03 \x01(\t\x12\x0b\n\x03\x64ob\x18\x04 \x01(\t\x12\r\n\x05\x65mail\x18\x05 \x03(\t\x12\x19\n\x06person\x18\x06 \x03(\x0b\x32\t.relative\"C\n\x08relative\x12\x14\n\x0crelationship\x18\x01 \x01(\t\x12\x10\n\x08relaName\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t22\n\ngetStudent\x12$\n\x07getByID\x12\t.inputSID\x1a\x0c.studentInfo\"\x00\x62\x06proto3'
)




_INPUTSID = _descriptor.Descriptor(
  name='inputSID',
  full_name='inputSID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sid', full_name='inputSID.sid', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=49,
)


_STUDENTINFO = _descriptor.Descriptor(
  name='studentInfo',
  full_name='studentInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sid', full_name='studentInfo.sid', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='studentInfo.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gender', full_name='studentInfo.gender', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dob', full_name='studentInfo.dob', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='email', full_name='studentInfo.email', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='person', full_name='studentInfo.person', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=162,
)


_RELATIVE = _descriptor.Descriptor(
  name='relative',
  full_name='relative',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='relationship', full_name='relative.relationship', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='relaName', full_name='relative.relaName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='address', full_name='relative.address', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=231,
)

_STUDENTINFO.fields_by_name['person'].message_type = _RELATIVE
DESCRIPTOR.message_types_by_name['inputSID'] = _INPUTSID
DESCRIPTOR.message_types_by_name['studentInfo'] = _STUDENTINFO
DESCRIPTOR.message_types_by_name['relative'] = _RELATIVE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

inputSID = _reflection.GeneratedProtocolMessageType('inputSID', (_message.Message,), {
  'DESCRIPTOR' : _INPUTSID,
  '__module__' : 'proto.getStudent_pb2'
  # @@protoc_insertion_point(class_scope:inputSID)
  })
_sym_db.RegisterMessage(inputSID)

studentInfo = _reflection.GeneratedProtocolMessageType('studentInfo', (_message.Message,), {
  'DESCRIPTOR' : _STUDENTINFO,
  '__module__' : 'proto.getStudent_pb2'
  # @@protoc_insertion_point(class_scope:studentInfo)
  })
_sym_db.RegisterMessage(studentInfo)

relative = _reflection.GeneratedProtocolMessageType('relative', (_message.Message,), {
  'DESCRIPTOR' : _RELATIVE,
  '__module__' : 'proto.getStudent_pb2'
  # @@protoc_insertion_point(class_scope:relative)
  })
_sym_db.RegisterMessage(relative)



_GETSTUDENT = _descriptor.ServiceDescriptor(
  name='getStudent',
  full_name='getStudent',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=233,
  serialized_end=283,
  methods=[
  _descriptor.MethodDescriptor(
    name='getByID',
    full_name='getStudent.getByID',
    index=0,
    containing_service=None,
    input_type=_INPUTSID,
    output_type=_STUDENTINFO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GETSTUDENT)

DESCRIPTOR.services_by_name['getStudent'] = _GETSTUDENT

# @@protoc_insertion_point(module_scope)
